name: Upload Image to ghcr.io
run-name: Uploading ${{ github.actor }}'s changes - "${{ github.event.head_commit.message }}"

on:
        workflow_dispatch:
        push:
        schedule:
                - cron: '0 0 * * 0'
env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
        push-github:
                runs-on: ubuntu-latest
                name: Build & Push images to Github registry
                env:
                        REGISTRY: ghcr.io
                outputs:
                        image_name: ${{ steps.setName.outputs.lowercase_image_name }}

                steps:
                        - name: Set up Image Name
                          id: setName
                          run: |
                                  IMAGE_NAME=${{ github.repository }}
                                  echo "::set-output name=lowercase_image_name::$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')"
                                  echo "IMAGE_NAME=${IMAGE_NAME}"

                        - name: Checkout Repository
                          uses: actions/checkout@v4.1.1

                        - name: Set up Docker buildx
                          uses: docker/setup-buildx-action@v3.0.0
                          with:
                                  driver-opts: |
                                          image=moby/buildkit:v0.12.4

                        - name: Log into registry ${{ env.REGISTRY }}
                          uses: docker/login-action@v3.0.0
                          with:
                                  registry: ghcr.io
                                  username: ${{ github.actor }}
                                  password: ${{ secrets.GITHUB_TOKEN }}

                        - name: Build and push Docker image - latest
                          uses: docker/build-push-action@v5.1.0
                          with:
                                  tags: ghcr.io/${{ steps.setName.outputs.lowercase_image_name }}:latest
                                  push: true
